M48
; DRILL file {KiCad 9.0.7} date 2026-09-13T13:28:07+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-13T13:28:07+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.150
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X204.8Y-90.5
T2
X225.8Y-90.5
T3
X148.5Y-70.75
M30
